### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by futurelucas4502** [snuutti/pallokala#1]
**Describe the bug**

An indexOf error
Stack trace: (ofc I'm the first bug report :)) 

```
TypeError: Cannot read property 'indexOf' of undefined
    at hasScope (address at index.android.bundle:1:1760138)
    at anonymous (address at index.android.bundle:1:1902718)
    at updateMemo (address at index.android.bundle:1:388960)
    at anonymous (address at index.android.bundle:1:218573)
    at DrawerHeaderButton (address at index.android.bundle:1:1901760)
    at renderWithHooks (address at index.android.bundle:1:385483)
    at updateFunctionComponent (address at index.android.bundle:1:394688)
    at beginWork (address at index.android.bundle:1:433152)
    at performUnitOfWork (address at index.android.bundle:1:419793)
    at workLoopSync (address at index.android.bundle:1:418923)
    at renderRootSync (address at index.android.bundle:1:418754)
    at flushSyncWorkAcrossRoots_impl (address at index.android.bundle:1:375184)
    at scheduleUpdateOnFiber (address at index.android.bundle:1:416259)
    at dispatchSetState (address at index.android.bundle:1:389897)
    at anonymous (address at index.android.bundle:1:1914523)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (address at index.android.bundle:1:147559)
    at _callTimer (address at index.android.bundle:1:146558)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:146702)
    at callReactNativeMicrotasks (address at index.android.bundle:1:148633)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:112324)
    at anonymous (address at index.android.bundle:1:111459)
    at __guard (address at index.android.bundle:1:112198)
    at flushedQueue (address at index.android.bundle:1:111370)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:111226)
```

**To Reproduce**
1. Logged into http server with a port defined at the end or the URL 
2. Click on went into my servers and clicked the only one I have and crash

**Expected behavior**

To open the server page

**Screenshots**

**Device**
 - Model: Samsung s23 ultra
 - OS: Android 14
 - App Version 1.1.0

**Additional context**

**Comment by snuutti** [comment]
What's your PufferPanel version? This looks like something that I've seen happen when logging into a 2.0 server.
Right now there's only support for version 3.0 PufferPanel servers.

I'll probably look into adding support for 2.0 servers later this week if it doesn't require too many code changes.

**Comment by futurelucas4502** [comment]
Ah you're right that's my fault I thought my panel version was newer than it was
